apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: nextjs-web-app-dev
description: Delivery pipeline for NextJS web app
serialPipeline:
  stages:
  - targetId: nextjs-web-app-dev-target
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nextjs-web-app-dev-target
description: Cloud Run target for NextJS web app
run:
  location: ${REGION}