apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nextjs-web-app-dev
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: app
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi