name: Continuous Integration

on:
  push:
    branches: [ dev, stage, main ]
  pull_request:
    branches: [ dev, stage, main ]
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Type check with TypeScript
        run: npx tsc --noEmit
      
      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Run security checks
        run: |
          if [ -f "./scripts/security_check.sh" ]; then
            chmod +x ./scripts/security_check.sh
            ./scripts/security_check.sh
          else
            echo "Security check script not found, skipping..."
          fi