name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGION: us-central1
  SERVICE_NAME: nextjs-app

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI
        uses: ./.github/actions/ci

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: ci
    environment: production
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloud Run
        uses: ./.github/actions/deploy-to-cloudrun
        with:
          workload-identity-provider: ${{ secrets.WIF_PROVIDER_PROD }}
          service-account: ${{ secrets.SA_EMAIL_PROD }}
          project-id: ${{ secrets.PROJECT_ID_PROD }}
          artifact-registry-repo: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          region: ${{ env.REGION }}
          service-name: ${{ env.SERVICE_NAME }}
          environment: 'production'
          memory: '2Gi'
          cpu: '2'
          min-instances: '2'
          max-instances: '50'
          enable-traffic-splitting: 'true'