name: Deploy to Dev

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!stage'
  workflow_dispatch:

env:
  REGION: us-central1
  SERVICE_NAME: nextjs-app

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI
        uses: ./.github/actions/ci

  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/stage'
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloud Run
        uses: ./.github/actions/deploy-to-cloudrun
        with:
          workload-identity-provider: ${{ secrets.WIF_PROVIDER_DEV }}
          service-account: ${{ secrets.SA_EMAIL_DEV }}
          project-id: ${{ secrets.PROJECT_ID_DEV }}
          artifact-registry-repo: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          region: ${{ env.REGION }}
          service-name: ${{ env.SERVICE_NAME }}
          environment: 'dev'
          memory: '512Mi'
          cpu: '1'
          min-instances: '0'
          max-instances: '10'