name: Deploy to Stage

on:
  push:
    branches: [stage]
  workflow_dispatch:

env:
  REGION: us-central1
  SERVICE_NAME: nextjs-app

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI
        uses: ./.github/actions/ci

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: ci
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloud Run
        uses: ./.github/actions/deploy-to-cloudrun
        with:
          workload-identity-provider: ${{ secrets.WIF_PROVIDER_STAGE }}
          service-account: ${{ secrets.SA_EMAIL_STAGE }}
          project-id: ${{ secrets.PROJECT_ID_STAGE }}
          artifact-registry-repo: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
          region: ${{ env.REGION }}
          service-name: ${{ env.SERVICE_NAME }}
          environment: 'stage'
          memory: '1Gi'
          cpu: '1'
          min-instances: '1'
          max-instances: '20'